//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionsWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public long ID { get; set; }
        public int UserID { get; set; }
        public int DayInWeek { get; set; }
        public System.DateTime TimeInDay { get; set; }
        public int EventID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual events events { get; set; }
        public virtual users users { get; set; }
    }
}
